<?php
	Class libYSBOSSLanguages {
		static function getList(){
			// Country => array(region code, language code)
			return array(
				'Disabled'=>NULL,
				'Argentina'=>array('ar','es'),
				'Austria'=>array('at','de'),
				'Australia'=>array('au','en'),
				'Brazil'=>array('br','pt'),
				'Canada - English'=>array('ca','en'),
				'Canada - French'=>array('ca','fr'),
				'Catalan'=>array('ct','ca'),
				'Chile'=>array('cl','es'),
				'Columbia'=>array('co','es'),
				'Denmark'=>array('dk','da'),
				'Finland'=>array('fi','fi'),
				'French'=>array('fr','fr'),
				'German'=>array('de','de'),
				'Indonesia - English'=>array('id','en'),
				'Indonesia - Indonesian'=>array('id','id'),
				'India'=>array('in','en'),
				'Israel'=>array('il','he'),
				'Italian'=>array('it','it'),
				'Japan'=>array('jp','jp'),
				'Korea'=>array('kr','kr'),
				'Malaysia - English'=>array('my','en'),
				'Malaysia'=>array('my','ms'),
				'Mexico'=>array('mx','es'),
				'Netherlands'=>array('nl','nl'),
				'New Zealand'=>array('nz','en'),
				'Norway'=>array('no','no'),
				'Peru'=>array('pe','es'),
				'Philippines'=>array('ph','tl'),
				'Philippines - English'=>array('ph','en'),
				'Romania'=>array('ro','ro'),
				'Russia'=>array('ru','ru'),
				'Singapore'=>array('sg','en'),
				'Spanish'=>array('es','es'),
				'Sweden'=>array('se','sv'),
				'Switzerland - French'=>array('ch','fr'),
				'Switzerland - German'=>array('ch','de'),
				'Switzerland - Italian'=>array('ch','it'),
				'Thailand'=>array('th','th'),
				'Turkey'=>array('tr','tr'),
				'United Kingdom'=>array('uk','en'),
				'United States - English'=>array('us','en'),
				'United States - Spanish'=>array('us','es'),
				'Venezuela'=>array('ve','es'),
				'Vietnam'=>array('vn','vi'),
			);
		}
	}
?>